hosts:
  - host: 192.168.0.1
    description: Главный роутер

  - host: 192.168.0.200
    description: Камера 1

  - host: google.com
    description: Google
    
  - host: 192.168.0.22
    description: Роутер_15

  - host: 192.168.0.23
    description: Роутер_22
